[package]
name = "sriail/scramjet-browser"
version = "0.1.0"
description = "Scramjet Browser"

[[module]]
name = "static-server"
source = "wasmer/static-web-server:0.1.0"

[[command]]
name = "serve"
module = "static-server"

[fs]
# Map your local "src" folder to "/public" inside the server context
"/public" = "src"
